import { PrismaClient } from '@prisma/client';
import NextAuth from 'next-auth';
import Providers from 'next-auth/providers';

import Adapter from 'db/prisma/prisma-next-auth-adapter';
import jwt from 'utils/jwt';

// Change it to default prisma adapter once it's fixed
// https://github.com/nextauthjs/next-auth/issues/683

const i = 0;
const prisma = new PrismaClient();
const options = {
  // TODO Create branded pages for autogenerated pages
  pages: {
    signIn: '/login',
  },
  providers: [
    Providers.GitHub({
      clientId: process.env.GITHUB_CLIENT_ID,
      clientSecret: process.env.GITHUB_CLIENT_SECRET,
    }),
  ],
  session: {
    maxAge: 90 * 24 * 60 * 60,
  },
  callbacks: {
    session: async (session, user) => {
      const token = jwt.encode(user, session.expires);
      session.token = token;
      return Promise.resolve(session);
    },
  },
  adapter: Adapter({ prisma }),
};

export default (req, res) => NextAuth(req, res, options);
